# Generated by Django 4.1.1 on 2022-12-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_watch_time_alter_video_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
    ]
