# Generated by Django 4.1.1 on 2022-12-27 16:10

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_verfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
