# Generated by Django 4.1.1 on 2022-12-27 16:47

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='videos_vide_search__29b818_gin'),
        ),
    ]
