# Generated by Django 4.1.1 on 2022-12-27 16:48

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def compute_search_vector(apps, schema_editor):
    Video = apps.get_model("videos", "Video")
    Video.objects.update(search_vector=SearchVector("search_text"))


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_video_videos_vide_search__29b818_gin"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE OF search_text, search_vector
            ON videos_video
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', search_text
            );
            UPDATE videos_video SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON videos_video;
            """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
