# Generated by Django 4.1.1 on 2022-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_create_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
