# Generated by Django 4.1.1 on 2026-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_cast_alter_video_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
