# Generated by Django 4.1.1 on 2026-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
