# Generated by Django 4.1.1 on 2026-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
    ]
