# Generated by Django 4.1.1 on 2026-03-10 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebridVideo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024, unique=True)),
                ('title', models.CharField(max_length=2048)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=1024, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('movie_id', models.CharField(blank=True, max_length=25, null=True)),
                ('search_text', models.CharField(blank=True, max_length=4096, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=1024, null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('watch_time', models.IntegerField(blank=True, default=0, null=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
