# Generated by Django 4.1.1 on 2026-03-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_debridvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
