# Generated by Django 4.1.1 on 2026-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_debridvideo_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
