# Generated by Django 4.1.1 on 2026-03-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_debridvideo_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='parent_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
