# Generated by Django 4.1.1 on 2026-03-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_debridvideo_parent_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='url_id',
            field=models.CharField(default='NA', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debridvideo',
            name='url',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
