# Generated by Django 4.1.1 on 2026-03-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_debridvideo_url_id_alter_debridvideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debridvideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
