# Generated by Django 4.1.1 on 2026-03-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_debridvideo_deleted_at_debridvideo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='parent_title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
