# Generated by Django 4.1.1 on 2026-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_debridvideo_parent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='debrid_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
