# Generated by Django 4.1.1 on 2026-03-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_debridvideo_debrid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='debrid_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
