# Generated by Django 4.1.1 on 2026-03-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_debridfiles_search_text'),
        ('videos', '0020_debridvideo_debrid_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debridvideo',
            name='debrid_id',
        ),
        migrations.RemoveField(
            model_name='debridvideo',
            name='parent_hash',
        ),
        migrations.RemoveField(
            model_name='debridvideo',
            name='parent_title',
        ),
        migrations.RemoveField(
            model_name='debridvideo',
            name='url_id',
        ),
        migrations.AddField(
            model_name='debridvideo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='backend.debridfiles'),
        ),
    ]
