# Generated by Django 4.1.1 on 2026-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_remove_debridvideo_debrid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debridvideo',
            name='url',
        ),
        migrations.AddField(
            model_name='debridvideo',
            name='download_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='debridvideo',
            name='unrestricted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
