# Generated by Django 4.1.1 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_remove_debridvideo_url_debridvideo_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='extention',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
