# Generated by Django 4.1.1 on 2026-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_debridvideo_extention'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='timeouts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
