# Generated by Django 4.1.1 on 2026-04-04 05:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_debridvideo_timeouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridvideo',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='debridvideo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='videos_debr_search__4c307a_gin'),
        ),
    ]
