# Generated by Django 4.1.1 on 2022-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='is_superstar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='star',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
