# Generated by Django 4.1.1 on 2022-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_navbar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
