# Generated by Django 4.1.1 on 2022-10-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_star_is_superstar_alter_star_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='resolution',
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
