# Generated by Django 4.1.1 on 2022-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_video_resolution_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='movie_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
