# Generated by Django 4.1.1 on 2022-11-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_navbar_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
