# Generated by Django 4.1.1 on 2022-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_video_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='scrubber',
            new_name='scrubber_sprite',
        ),
        migrations.AddField(
            model_name='video',
            name='scrubber_vtt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
