# Generated by Django 4.1.1 on 2022-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_category_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
