# Generated by Django 4.1.1 on 2022-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_series_created_series_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='categories',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
