# Generated by Django 4.1.1 on 2022-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_scrubber_video_scrubber_sprite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_poster',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
