# Generated by Django 4.1.1 on 2022-10-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_video_preview_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
