# Generated by Django 4.1.1 on 2022-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_video_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='search_text',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
