# Generated by Django 4.1.1 on 2022-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_userleveldata_scan_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleveldata',
            name='scanning',
            field=models.BooleanField(default=False),
        ),
    ]
