# Generated by Django 4.1.1 on 2022-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_video_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cast',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
