# Generated by Django 4.1.1 on 2022-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_video_cast_alter_video_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
