# Generated by Django 4.1.1 on 2022-12-27 16:48

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def compute_search_vector(apps, schema_editor):
    Category = apps.get_model("backend", "Category")
    Category.objects.update(search_vector=SearchVector("title"))


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_category_search_vector_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE OF title, search_vector
            ON backend_category
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', title
            );
            UPDATE backend_category SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON backend_category;
            """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
