# Generated by Django 4.1.1 on 2022-10-16 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_video_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('videos', models.IntegerField(blank=True, default=0, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='episodes', to='backend.series'),
        ),
    ]
