# Generated by Django 4.1.1 on 2022-10-19 14:36

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_series_alter_video_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='preview_poster',
            new_name='preview_thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='episode',
        ),
        migrations.AlterField(
            model_name='category',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.upload_category_poster),
        ),
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='backend.series'),
        ),
    ]
