# Generated by Django 4.1.1 on 2023-01-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_series_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
