# Generated by Django 4.1.1 on 2022-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_preview_poster_video_preview_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='is_favourite',
            new_name='favourite',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='is_superstar',
            new_name='superstar',
        ),
        migrations.AlterField(
            model_name='video',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
