# Generated by Django 4.1.1 on 2023-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_navbar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleveldata',
            name='websrc_dir',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
