# Generated by Django 4.1.1 on 2024-05-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_userleveldata_websrc_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleveldata',
            name='uf_jt_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
