# Generated by Django 4.1.1 on 2026-01-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_userleveldata_uf_jt_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleveldata',
            name='click_to_skip',
            field=models.BooleanField(default=False),
        ),
    ]
