# Generated by Django 4.1.1 on 2026-03-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_userleveldata_click_to_skip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebridFiles',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('debrid_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=1024)),
                ('hash', models.CharField(max_length=40)),
                ('size', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('is_imported', models.BooleanField(blank=True, default=False, null=True)),
                ('import_timestamp', models.DateTimeField(blank=True, null=True)),
                ('files', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
