# Generated by Django 4.1.1 on 2026-03-14 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_debridfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridfiles',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
