# Generated by Django 4.1.1 on 2026-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_debridfiles_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridfiles',
            name='importing',
            field=models.BooleanField(default=False),
        ),
    ]
