# Generated by Django 4.1.1 on 2026-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_debridfiles_importing'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridfiles',
            name='task_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
