# Generated by Django 4.1.1 on 2026-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_debridfiles_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debridfiles',
            name='task_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
