# Generated by Django 4.1.1 on 2026-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_debridfiles_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridfiles',
            name='search_text',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
