# Generated by Django 4.1.1 on 2026-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_debridfiles_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridfiles',
            name='in_debrid',
            field=models.BooleanField(default=True),
        ),
    ]
