# Generated by Django 4.1.1 on 2026-04-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_debridfiles_in_debrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debridfiles',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
