# Generated by Django 4.1.1 on 2022-10-21 15:45

from django.db import migrations, models
import django.utils.timezone
import stars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('favourite', models.BooleanField(default=False)),
                ('superstar', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('videos', models.IntegerField(blank=True, default=0, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=stars.models.upload_star_poster)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=stars.models.upload_star_banner)),
                ('tags', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
