# Generated by Django 4.1.1 on 2022-12-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='favourite',
            new_name='liked',
        ),
    ]
