# Generated by Django 4.1.1 on 2022-12-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_rename_favourite_star_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='superstar',
            new_name='favourite',
        ),
    ]
