# Generated by Django 4.1.1 on 2022-12-27 17:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_rename_superstar_star_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='star',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='stars_star_search__9cefe0_gin'),
        ),
    ]
