# Generated by Django 4.1.1 on 2022-12-27 16:48

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def compute_search_vector(apps, schema_editor):
    Star = apps.get_model("stars", "Star")
    Star.objects.update(search_vector=SearchVector("name"))


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0004_star_search_vector_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE OF name, search_vector
            ON stars_star
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', name
            );
            UPDATE stars_star SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON stars_star;
            """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
