# Generated by Django 4.1.1 on 2023-01-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_create_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='watchtime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
