# Generated by Django 4.1.1 on 2025-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_star_watchtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='totaltime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
